"""Deterministic safe SVG geometry from accepted exact plot values."""

from __future__ import annotations

import html
from decimal import Decimal, localcontext
from fractions import Fraction
from pathlib import Path

from arw.kernel.core.canonical import sha256_hex
from arw.kernel.state.research_artifact import RendererIdentity

from .plot_policy import PlotFault, validate_svg_safety
from .renderer import _text

OKABE_ITO = (
    "#000000",
    "#E69F00",
    "#56B4E9",
    "#009E73",
    "#F0E442",
    "#0072B2",
    "#D55E00",
    "#CC79A7",
)


def _number(value):
    """Round layout only, after exact fractions determined coordinates."""
    with localcontext() as ctx:
        ctx.prec = 160
        number = Decimal(value.numerator) / Decimal(value.denominator)
        return (
            format(number.quantize(Decimal("0.000001")), "f").rstrip("0").rstrip(".")
            or "0"
        )


def _log(value):
    if value <= 0:
        raise PlotFault("log_value_out_of_domain")
    with localcontext() as ctx:
        ctx.prec = 400
        return Fraction((Decimal(value.numerator) / Decimal(value.denominator)).ln())


class PlotRenderer:
    @property
    def identity(self):
        # Include shared safety/layout source, because both affect generated bytes.
        own = Path(__file__).read_bytes()
        policy = Path(__file__).with_name("plot_policy.py").read_bytes()
        return RendererIdentity(
            name="arw.result-svg",
            version="1.0.0",
            identity_digest=sha256_hex(
                own
                + b"\0"
                + policy
                + b"\0"
                + Path(__file__).with_name("renderer.py").read_bytes()
            ),
            normalization_policy="utf8-lf-exact-fraction-decimal400-log-layout6.v1",
        )

    def render(self, compiled):
        ir = compiled.ir
        width, height = ir.presentation.width, ir.presentation.height
        left, right, top, bottom = (
            Fraction(90),
            Fraction(width - 40),
            Fraction(80),
            Fraction(height - 180),
        )
        all_data = [d for _, rows in compiled.layers for d in rows]
        categories = ir.scales.x.categories or tuple(
            sorted({d.category for d in all_data})
        )
        series = tuple(sorted({d.series for d in all_data}))
        named_series = tuple(s for s in series if s)
        palette = OKABE_ITO if ir.presentation.palette == "okabe_ito" else ("#222222",)
        colors = {s: palette[i % len(palette)] for i, s in enumerate(series)}
        if len(series) > 8:
            raise PlotFault("series_budget_exceeded")

        def domain(scale, channel):
            vals = [
                v.exact.as_fraction()
                for v in compiled.plot_values
                if (v.channel == "x") == (channel == "x")
            ]
            if channel == "y" and any(layer.mark == "bar" for layer in ir.layers):
                vals.append(Fraction(0))
            if not vals:
                raise PlotFault("empty_numeric_domain")
            if scale.type == "log" and any(v <= 0 for v in vals):
                raise PlotFault("log_value_out_of_domain")
            if scale.domain:
                lo, hi = (v.as_fraction() for v in scale.domain)
                if min(vals) < lo or max(vals) > hi:
                    raise PlotFault("value_outside_explicit_domain")
            else:
                lo, hi = min(vals), max(vals)
                if lo == hi:
                    if scale.type == "log":
                        lo, hi = lo / 2, hi * 2
                    else:
                        lo, hi = lo - 1, hi + 1
                elif scale.type != "log":
                    pad = (hi - lo) / 20
                    lo, hi = lo - pad, hi + pad
            return lo, hi

        y_domain = domain(ir.scales.y, "y")
        x_domain = None if ir.scales.x.type == "band" else domain(ir.scales.x, "x")

        def numeric_position(value, scale, limits, start, end):
            lo, hi = limits
            if scale.type == "log":
                lo, hi, value = _log(lo), _log(hi), _log(value)
            if hi == lo:
                raise PlotFault("log_layout_precision_unsupported")
            return start + (value - lo) * (end - start) / (hi - lo)

        def xy(d, layer, endpoint=None):
            if ir.scales.x.type == "band":
                if d.category not in categories:
                    raise PlotFault("category_outside_explicit_domain")
                x = left + (Fraction(categories.index(d.category)) + Fraction(1, 2)) * (
                    right - left
                ) / len(categories)
                band_width = (right - left) / len(categories)
                group_width = min(Fraction(24), band_width / (len(named_series) + 2))
                if d.series and len(named_series) > 1:
                    x += (
                        Fraction(named_series.index(d.series))
                        - Fraction(len(named_series) - 1, 2)
                    ) * group_width
                if layer.jitter_axis:
                    if not d.stable_row_id:
                        raise PlotFault("jitter_requires_stable_row_id")
                    digest = int(sha256_hex(d.stable_row_id.encode("utf-8"))[:16], 16)
                    jitter = Fraction(digest, 2**64 - 1) - Fraction(1, 2)
                    x += jitter * group_width * Fraction(2, 5)
            else:
                x = numeric_position(
                    d.x.exact.as_fraction(), ir.scales.x, x_domain, left, right
                )
            val = endpoint or d.y
            y = numeric_position(
                val.exact.as_fraction(), ir.scales.y, y_domain, bottom, top
            )
            return x, y

        parts = [
            f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}" role="img">',
            f"<title>{html.escape(ir.title)}</title>",
            "<desc>Single-panel exact-source result plot. SVG byte determinism does not certify host fonts or publication quality.</desc>",
            f'<g font-family="{ir.presentation.font_family}" fill="#222222">',
            _text(ir.title, 30, 35, 88, 20),
            f'<line x1="{_number(left)}" y1="{_number(bottom)}" x2="{_number(right)}" y2="{_number(bottom)}" stroke="#222222"/>',
            f'<line x1="{_number(left)}" y1="{_number(top)}" x2="{_number(left)}" y2="{_number(bottom)}" stroke="#222222"/>',
        ]
        # Exact rational ticks (log domain uses fixed Decimal geometric ticks).
        for i in range(5):
            if ir.scales.y.type == "log":
                with localcontext() as ctx:
                    ctx.prec = 400
                    lo, hi = (_log(v) for v in y_domain)
                    tick = Fraction(
                        (
                            Decimal((lo + (hi - lo) * Fraction(i, 4)).numerator)
                            / Decimal((lo + (hi - lo) * Fraction(i, 4)).denominator)
                        ).exp()
                    )
            else:
                tick = y_domain[0] + (y_domain[1] - y_domain[0]) * Fraction(i, 4)
            y = numeric_position(tick, ir.scales.y, y_domain, bottom, top)
            parts += [
                f'<line x1="85" y1="{_number(y)}" x2="90" y2="{_number(y)}" stroke="#222222"/>',
                _text(_number(tick), 8, _number(y + 4), 18, 11),
            ]
        if ir.scales.x.type == "band":
            for i, category in enumerate(categories):
                x = left + (Fraction(i) + Fraction(1, 2)) * (right - left) / len(
                    categories
                )
                parts.append(
                    _text(category, _number(x - 20), _number(bottom + 22), 18, 11)
                )
        else:
            for i in range(5):
                lo, hi = x_domain
                if ir.scales.x.type == "log":
                    with localcontext() as ctx:
                        ctx.prec = 400
                        log_tick = _log(lo) + (_log(hi) - _log(lo)) * Fraction(i, 4)
                        tick = Fraction(
                            (
                                Decimal(log_tick.numerator)
                                / Decimal(log_tick.denominator)
                            ).exp()
                        )
                else:
                    tick = lo + (hi - lo) * Fraction(i, 4)
                x = numeric_position(tick, ir.scales.x, x_domain, left, right)
                parts.append(
                    _text(_number(tick), _number(x - 15), _number(bottom + 22), 18, 11)
                )
        parts += [
            _text(ir.scales.y.unit, 8, 65, 20, 12),
            _text(ir.scales.x.unit, 90, height - 115, 40, 12),
        ]
        for layer, rows in compiled.layers:
            parts.append(f'<g id="{layer.layer_id}">')
            if layer.mark == "line":
                groups = sorted(
                    {(d.series, d.pair_id if layer.paired else None) for d in rows},
                    key=lambda k: (k[0], k[1] or ""),
                )
                for group in groups:
                    ordered = sorted(
                        (
                            d
                            for d in rows
                            if (d.series, d.pair_id if layer.paired else None) == group
                        ),
                        key=lambda d: d.order,
                    )
                    positions = [xy(d, layer) for d in ordered]
                    path = " ".join(
                        f"{'M' if i == 0 else 'L'} {_number(x)} {_number(y)}"
                        for i, (x, y) in enumerate(positions)
                    )
                    parts.append(
                        f'<path d="{path}" fill="none" stroke="{colors[group[0]]}" stroke-width="2"/>'
                    )
            for d in rows:
                color = colors[d.series]
                if layer.role == "interval":
                    x, lower = xy(d, layer, d.lower)
                    _, upper = xy(d, layer, d.upper)
                    parts += [
                        f'<g id="{d.lower.plot_value_id}"><line x1="{_number(x)}" y1="{_number(lower)}" x2="{_number(x)}" y2="{_number(upper)}" stroke="{color}" stroke-width="2"/>',
                        f'<line x1="{_number(x - 5)}" y1="{_number(lower)}" x2="{_number(x + 5)}" y2="{_number(lower)}" stroke="{color}"/>',
                        f'<line id="{d.upper.plot_value_id}" x1="{_number(x - 5)}" y1="{_number(upper)}" x2="{_number(x + 5)}" y2="{_number(upper)}" stroke="{color}"/></g>',
                    ]
                    continue
                x, y = xy(d, layer)
                if layer.mark == "bar":
                    zero = numeric_position(
                        Fraction(0), ir.scales.y, y_domain, bottom, top
                    )
                    parts.append(
                        f'<rect id="{d.y.plot_value_id}" x="{_number(x - 10)}" y="{_number(min(y, zero))}" width="20" height="{_number(abs(y - zero))}" fill="{color}"/>'
                    )
                else:
                    parts.append(
                        f'<circle id="{d.y.plot_value_id}" cx="{_number(x)}" cy="{_number(y)}" r="4" fill="{color}"/>'
                    )
            # Legends, captions and manuscript references are always inert text.
            parts.append("</g>")
        legend_columns = max(1, (width - 140) // 110)
        for i, s in enumerate(named_series):
            if s:
                lx, ly = (
                    90 + (i % legend_columns) * 110,
                    height - 110 + (i // legend_columns) * 16,
                )
                parts += [
                    f'<rect x="{lx}" y="{ly}" width="10" height="10" fill="{colors[s]}"/>',
                    _text(s, lx + 15, ly + 10, 16, 11),
                ]
        parts += [_text(ir.caption, 30, height - 65, 95, 12), "</g>", "</svg>"]
        output = ("\n".join(parts) + "\n").encode("utf-8")
        validate_svg_safety(output)
        return output
